### ISSUE TITLE
Compiling error on Fedora 40

### ISSUE THREAD

**Issue by Felix-Halder** [itsjunetime/tdf#20] opened 2024-10-17 21:40 UTC
I get the following error when trying to build:

cargo build --release
warning: file `/home/<User>/Utilities/tdf/./benches/for_profiling.rs` found to be present in multiple build targets:
  * `bin` target `for_profiling`
  * `bench` target `for_profiling`
   Compiling libc v0.2.159
   Compiling serde v1.0.210
   Compiling proc-macro2 v1.0.87
   Compiling target-lexicon v0.12.16
   Compiling crossbeam-utils v0.8.20
   Compiling rustversion v1.0.17
   Compiling indexmap v2.6.0
   Compiling lock_api v0.4.12
   Compiling slab v0.4.9
   Compiling signal-hook v0.3.17
   Compiling futures-task v0.3.31
   Compiling either v1.13.0
   Compiling parking_lot_core v0.9.10
   Compiling adler2 v2.0.0
   Compiling byteorder v1.5.0
   Compiling rustix v0.38.37
   Compiling rayon-core v1.12.1
   Compiling bitflags v1.3.2
   Compiling futures-channel v0.3.31
   Compiling crc32fast v1.4.2
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

   Compiling num-traits v0.2.19
error: could not compile `lock_api` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `signal-hook` (build script) due to 1 previous error
error: could not compile `slab` (build script) due to 1 previous error
error: could not compile `rayon-core` (build script) due to 1 previous error
error: could not compile `num-traits` (build script) due to 1 previous error
error: could not compile `serde` (build script) due to 1 previous error
error: could not compile `crossbeam-utils` (build script) due to 1 previous error
error: could not compile `proc-macro2` (build script) due to 1 previous error
error: could not compile `parking_lot_core` (build script) due to 1 previous error
error: could not compile `rustix` (build script) due to 1 previous error
error: could not compile `rustversion` (build script) due to 1 previous error
error: could not compile `libc` (build script) due to 1 previous error
error: could not compile `target-lexicon` (build script) due to 1 previous error

**Comment by itsjunetime** [comment] 2024-10-26 21:04
It seems like you probably don't have a c compiler, such as `gcc`, installed. Try installing the `gcc` package and see if that fixes it.

**Comment by itsjunetime** [comment] 2024-12-01 20:23
I'm going to close this as it seems pretty clear what the issue is.

**Closed by itsjunetime** 2024-12-01 20:23 UTC
